#!/usr/bin/env bash

sudo curl -o /home/$SUDO_USER/prometheus.yml "https://github.com/micael-sjogren/cicd/blob/main/prometheus.yml"
sudo docker run --restart=always -d -p 9090:9090 -v /home/m/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
