#!/usr/bin/env bash

if ! command -v java &> /dev/null; then
    sudo dnf install java-1.8.0-openjdk -y
fi

if ! command -v docker &> /dev/null; then
    echo "Docker is not installed. Exiting."
    exit 1
fi

if ! command -v xclip &> /dev/null; then
    sudo dnf install xclip -y
fi

if ! docker ps -a | grep -q "jenkins_container"; then
    sudo docker run --restart=always -d -p 8080:8080 -p 50000:50000 --name jenkins_container jenkins/jenkins:lts
fi



