#!/usr/bin/env bash

if ! command -v java &> /dev/null; then
    sudo dnf install java-1.8.0-openjdk -y
fi

if ! command -v docker &> /dev/null; then
    echo "Docker is not installed. Exiting."
    exit 1
fi

if ! docker ps -a | grep -q "jenkins/jenkins:lts"; then
    sudo docker run --restart=always -d -p 8080:8080 -p 50000:50000 --name jenkins_container jenkins/jenkins:lts
fi

sleep 30

docker exec -it jenkins_container cat /var/jenkins_home/secrets/initialAdminPassword | xclip -selection clipboard

echo "Jenkins is installed and the initial admin password is copied to clipboard."
