#!/usr/bin/env bash

sudo rm -r /home/root/prometheus.yml
sudo curl -o /home/root/prometheus.yml "https://raw.githubusercontent.com/$GITHUB_USER/cicd/main/prometheus.yml"
sudo docker run --restart=always -d -p 9090:9090 -v /home/root/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus


